### ISSUE TITLE
Errors thrown from onCancel() are swallowed.

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/speculation#4]
An easy fix is to catch them, e.g.:

```js
const speculation = (
  fn, cancel = Promise.reject('Cancelled')
) => new Promise((resolve, reject) => {

  const handleCancel = (
    onCancel
  ) => cancel.then(onCancel).catch(e => {
    if (e.message !== 'Cancelled') reject(e);
  });

  return fn(resolve, reject, handleCancel);
});
```

But if you look closely, you'll notice that we need to be able to distinguish any random error thrown in `onCancel()` from the intentional `Cancelled` error. To do so, we'll need to clearly identify `Cancelled` errors. We could do that with a custom error type, or we could use the error message, as above.

It would be nice if users could pass a custom message, but I also don't want to be using `instanceof`. (Will we misidentify things if the custom error type is created in a different execution context?)

**Comment by ericelliott** [comment]
Another possible solution is to handle the normal cancel error with a noop and then catch the success handler's error with `.catch()`:

```js

**Comment by ajwhite** [comment]
Perhaps a custom error type?

```js
export const CancellationError = ...

const speculation = (
  fn, cancel = new Promise.reject(new CancellationError())
) ...
```

Where it would be easy to `catch` on the type
```js
import speculation, {CancellationError} from 'speculation';

const wait = ...

wait(200, wait(50))
  .then(() => console.log('Yerp'))
  .catch(e => {
    if (e instanceof CancellationError) ...
    else ...
  })
```

And much simpler with blurbird:

```js
.catch(CancellationError, () => console.log('Cancelled'))
.catch(e => console.log('failed', e))
```

**Comment by ericelliott** [comment]
`instanceof` lies when you try to use it across execution contexts.

**Comment by ajwhite** [comment]
Wow, good call.

Had an interesting read following up on this via https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_context_(e.g._frames_or_windows).
